kind: pipeline
type: docker
name: default
steps:
  - name: build
#    image: mobiledevops/flutter-sdk-image
    image: plugfox/flutter:master-web
    volumes:
      - name: build_web
        path: /drone/src/build/web
    commands:
      - ls
      - flutter upgrade --force
      - flutter build web --web-renderer html
      - tar -czvf target_web.tar.gz build/web
  - name: upload
    image: minio/mc:RELEASE.2024-01-16T16-06-34Z
    environment:
      ADDRESS:
        from_secret: MINIO_ADDRESS
      ACCESS_KEY:
        from_secret: MINIO_ACCESS_KEY
      SECRET_KEY:
        from_secret: MINIO_SECRET_KEY
    commands:
      - mc config host add mio $ADDRESS $ACCESS_KEY $SECRET_KEY
      - mc cp target_web.tar.gz mio/uchi
volumes:
  - name: build_web
    host:
      path: /mnt/user/appdata/drone/build/flutter/web
