kind: pipeline
type: docker
name: default
steps:
  - name: build
    image: mobiledevops/flutter-sdk-image
    volumes:
      - name: build_web
        path: /drone/src/build/web
    commands:
      - flutter pub outdated
      - flutter build web --web-renderer html
      - sleep 1000
  - name: upload
    image: minio/mc:RELEASE.2024-01-16T16-06-34Z
    environment:
      ADDRESS:
        from_secret: MINIO_ADDRESS
      ACCESS_KEY:
        from_secret: MINIO_ACCESS_KEY
      SECRET_KEY:
        from_secret: MINIO_SECRET_KEY
    commands:
      - mc config host add mio $ADDRESS $ACCESS_KEY $SECRET_KEY
      - mc cp CHANGES.md mio/uchi
      - mc cp app/build/outputs/apk/landscape/release/*.apk mio/uchi/apk/portrait
      - mc cp app/build/outputs/apk/portrait/release/*.apk mio/uchi/apk/landscape
volumes:
  - name: build_web
    host:
      path: /mnt/user/appdata/drone/build/flutter/web
